// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAevxJaD-G5qkWAfZqAFTIlj7lksxMPbOU',
    appId: '1:643518511719:web:b728a9fc02115395f1b2c2',
    messagingSenderId: '643518511719',
    projectId: 'chat-app-89495',
    authDomain: 'chat-app-89495.firebaseapp.com',
    storageBucket: 'chat-app-89495.appspot.com',
    measurementId: 'G-PWCJ50DRNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMs85bGXA9l8kEeDeIRVJpK7TqX_QmOEQ',
    appId: '1:643518511719:android:12e8d040a992c1c4f1b2c2',
    messagingSenderId: '643518511719',
    projectId: 'chat-app-89495',
    storageBucket: 'chat-app-89495.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPGHzlwsk0DNx3K1RXkx6UiffvZEj_HLU',
    appId: '1:643518511719:ios:7af03ed5bc5d9f3ef1b2c2',
    messagingSenderId: '643518511719',
    projectId: 'chat-app-89495',
    storageBucket: 'chat-app-89495.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPGHzlwsk0DNx3K1RXkx6UiffvZEj_HLU',
    appId: '1:643518511719:ios:8a556a235d0f4a67f1b2c2',
    messagingSenderId: '643518511719',
    projectId: 'chat-app-89495',
    storageBucket: 'chat-app-89495.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
